// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Button, ComboBox, Switch } from "std-widgets.slint";
import { Page } from "page.slint";

export component BaseSettingPage inherits Page {

    VerticalLayout {
        padding: 20px;
        spacing: 20px;
        HorizontalLayout {
            alignment: start;
            spacing: 20px;
            Text {
                text: @tr("语言");
                height: 30px;
                vertical-alignment: center;
            }
            ComboBox {
                width: 150px;
                height: 30px;
                model: ["简体中文", "English"];
                current-value: "简体中文";
            }
        }
        HorizontalLayout {
            alignment: start;
            spacing: 20px;
            Text {
                text: @tr("主题");
                height: 30px;
                vertical-alignment: center;
            }
            ComboBox {
                width: 150px;
                height: 30px;
                model: ["随系统", "暗色", "亮色"];
                current-value: "随系统";
            }
        }
        HorizontalLayout {
            alignment: start;
            spacing: 20px;
            Text {
                text: @tr("开机自启");
                height: 30px;
                vertical-alignment: center;
            }
            Switch { height: 30px; }
        }
    }
}
