// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox,
    Slider, ProgressIndicator, SpinBox, Switch } from "std-widgets.slint";
import { Page } from "page.slint";

export component SearchSettingPage inherits Page {
    VerticalLayout {
        alignment: start;
        padding: 20px;
        spacing: 20px;
        GroupBox {
            title: @tr("快捷键");
            VerticalLayout {
                spacing: 10px;
                HorizontalLayout {
                    alignment: start;
                    spacing: 20px;
                    Text {
                        text: @tr("搜索（全局）");
                        height: 30px;
                        width: 100px;
                        vertical-alignment: center;
                    }
                    LineEdit {
                        height: 30px;
                        read-only: true;
                        text: "Ctrl+F";
                    }
                }
            }
        }
    }
}
