[package]
name = "rotor-runtime"
version.workspace = true
edition = "2021"

[dependencies]
async-channel.workspace = true
global-hotkey.workspace = true
image.workspace = true
log.workspace = true
rotor-common.workspace = true
rotor-canvas.workspace = true
rotor-updater.workspace = true
rotor-platform.workspace = true
rotor-screenshot.workspace = true
rotor-searcher.workspace = true
rotor-translator.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time", "macros", "net"] }

[dev-dependencies]
tempfile.workspace = true
