import { Palette } from "std-widgets.slint";

component SideBarItem inherits Rectangle {
    in-out property<string> text <=> label.text;
    in property<bool> selected;
    callback clicked <=> touch.clicked;

    height: 26px;

    touch := TouchArea {
        state := Rectangle {
            border-radius: 5px;
            animate background { duration: 150ms; }

            label := Text {
                vertical-alignment: center;
                horizontal-alignment: center;
                font-size: 14px;
            }
        }
    }

    states [
        selected when root.selected : {
            state.background: dodgerblue;
        }
        hover when touch.has-hover : {
            state.background: dimgrey;
        }
    ]
}

export component SideBar inherits Rectangle {
    in property<[string]> model: [];
    out property<int> current-item: 0;
    width: 140px;

    Rectangle {
        background: Palette.background.darker(0.2);
        VerticalLayout {
            padding: 4px;
            spacing: 4px;
            alignment: start;

            for item[index] in root.model : SideBarItem {
                text: item;
                selected: index == root.current-item;
                clicked => { 
                    root.current-item = index;
                }
            }
        }
    }
}
