import { Palette } from "std-widgets.slint";
import { SimpleBtn, ButtonType } from "../frame/buttons.slint";

export component SideBar inherits Rectangle {
    width: 120px;
    background: Palette.background;

    in property<[string]> model: [];
    out property<int> current-item: 0;

    callback click_logo <=> logo_touch.clicked;
    
    VerticalLayout {
        alignment: start;
        padding-top: 10px;

        Rectangle {
            logo_touch := TouchArea {
                width: 50px;
                mouse-cursor: pointer;
                Image {
                    source: @image-url("../assets/icon/logo.svg");
                    height: 50px;
                }
            }
        }
        
        VerticalLayout {
            padding: 4px;
            spacing: 4px;
            alignment: start;

            for item[index] in root.model : SimpleBtn {
                height: 26px;
                border-radius: 5px;
                text: item;
                active: index == root.current-item;
                type: ButtonType.Text;
                hover_color: rgba(44,166,224,0.5);
                active_color: rgb(44,166,224);
                clicked => { 
                    root.current-item = index;
                }
            }
        }
    }
}