import { Palette } from "std-widgets.slint";

component SideBarItem inherits Rectangle {
    height: 26px;

    in property<bool> selected;
    in-out property<string> text <=> label.text;

    callback clicked <=> touch.clicked;

    touch := TouchArea {
        state := Rectangle {
            border-radius: 5px;
            label := Text {
                vertical-alignment: center;
                horizontal-alignment: center;
            }
        }
    }

    states [
        selected when root.selected : {
            state.background: rgb(44,166,224);
        }
        hover when touch.has-hover : {
            state.background: rgba(44,166,224,0.5);
        }
    ]
}

export component SideBar inherits Rectangle {
    width: 120px;
    background: Palette.background;

    in property<[string]> model: [];
    out property<int> current-item: 0;
    
    VerticalLayout {
        alignment: start;
        padding-top: 10px;

        Rectangle {
            width: 120px;
            Image {
                source: @image-url("../assets/icon/logo.svg");
                height: 50px;
            }
        }

        VerticalLayout {
            padding: 4px;
            spacing: 4px;
            alignment: start;

            for item[index] in root.model : SideBarItem {
                text: item;
                selected: index == root.current-item;
                clicked => { 
                    root.current-item = index;
                }
            }
        }
    }
}
