import { Palette } from "std-widgets.slint";

component TitleBtn inherits Rectangle {
    width: 40px;
    background: transparent;
    animate background { duration: 150ms; }

    in property<image> img <=> image.source;
    in property<color> hover_color;
    
    callback clicked <=> touch.clicked;

    touch := TouchArea {
        image := Image {
            height: 14px;
            width: 14px;
            colorize: Palette.foreground;
        }
    }

    states [
        pressed when touch.pressed : {
            root.background: hover_color.darker(0.5);
        }
        hover when touch.has-hover : {
            root.background: hover_color;
        }
    ]
}

export component TitleBar inherits Rectangle {
    height: 40px;
    width: 376px;
    background: Palette.background;

    callback minimize <=> min_btn.clicked;
    callback close <=> close_btn.clicked;

    HorizontalLayout {
        alignment: stretch;

        Rectangle {}

        min_btn := TitleBtn {
            img: @image-url("../assets/icon/min.svg");
            hover_color: Palette.selection-background;
        }

        close_btn := TitleBtn {
            img: @image-url("../assets/icon/close.svg");
            hover_color: red;
        }
    }
}
