import { Palette } from "std-widgets.slint";

import { SimpleBtn } from "../frame/buttons.slint";

export component TitleBar inherits Rectangle {
    height: 40px;
    width: 376px;
    background: Palette.background;

    callback minimize <=> min_btn.clicked;
    callback close <=> close_btn.clicked;

    HorizontalLayout {
        alignment: stretch;

        Rectangle {}

        min_btn := SimpleBtn {
            icon: @image-url("../assets/icon/min.svg");
        }

        close_btn := SimpleBtn {
            icon: @image-url("../assets/icon/close.svg");
            hover_color: red;
        }
    }
}
