[package]
name = "rotor-rs"
version = "0.1.0"
authors = ["Horbin"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
embed-resource = "2.2.0"

[dependencies]
chrono = "0.4.26"
global-hotkey = "0.2.4"
i-slint-backend-selector = "1.1.1"
i-slint-backend-winit = "1.1.1"
image = "0.24.7"
is-root = "0.1.3"
screenshots = "0.8.2"
tray-icon = "0.8.1"
winit = "0.28.6"
winreg = "0.51.0"

[dependencies.slint]
version = "1.1.1"
features = [
    "renderer-winit-skia-opengl",
]

[dependencies.windows-sys]
version = "0.48"
default-features = false
features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_System_IO",
    "Win32_System_Ioctl",
]
