import { AboutSlint, Button } from "std-widgets.slint";
import { Page } from "page.slint";

export component AboutPage inherits Page {
    in property <string> version: "unknown";

    callback check_update <=> check_update_btn.clicked;

    width: 100%;

    HorizontalLayout {
        alignment: center;
        padding-top: 40px;
        Rectangle {
            width: 100px;
            Image {
                source: @image-url("../../../../../../assets/logo.svg");
                height: 80px;
            }
        }
        VerticalLayout {
            alignment: center;
            Text {
                horizontal-alignment: center;
                text: "Rotor";
                font-size: 18px;
                font-weight: 700;
            }
            Text {
                horizontal-alignment: center;
                text: @tr("Version {}", version);
            }
            Text {
                horizontal-alignment: center;
                text: "by: Horibn";
            }
        }
    }

    check_update_btn := Button {
        text: "检查更新";
        width: 50%;
    }

    Text {
        horizontal-alignment: center;
        text: "查看本软件使用的开源库，感谢这些库的开发者！";
    }
}
