import { Button, ComboBox, Switch, GroupBox, LineEdit } from "std-widgets.slint";
import { Page } from "page.slint";

export component BaseSettingPage inherits Page {
    in-out property <bool> power_boot;
    in-out property <int> theme;
    in property <string> version: "unknown";

    callback theme_changed(int);
    callback power_boot_changed(bool);
    callback check_update();

    HorizontalLayout {
        alignment: start;
        spacing: 20px;
        Text {
            text: @tr("语言");
            height: 30px;
            vertical-alignment: center;
        }
        ComboBox {
            width: 150px;
            height: 30px;
            model: ["简体中文", "English"];
            current-index: 0;
            enabled: false;
        }
    }

    HorizontalLayout {
        alignment: start;
        spacing: 20px;
        Text {
            text: @tr("主题");
            height: 30px;
            vertical-alignment: center;
        }
        theme_box := ComboBox {
            width: 150px;
            height: 30px;
            model: ["跟随系统", "暗色", "亮色"];
            current-index: root.theme;
            enabled: false;
            selected(string) => {
                root.theme_changed(self.current-index);
            }
        }
    }

    HorizontalLayout {
        alignment: start;
        spacing: 20px;
        Text {
            text: @tr("开机自启");
            height: 30px;
            vertical-alignment: center;
        }
        Switch { 
            height: 30px;
            checked <=> root.power_boot;
            toggled => {
                root.power_boot_changed(self.checked);
            }
        }
    }

    GroupBox {
        title: @tr("全局快捷键");
        VerticalLayout {
            spacing: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("开始搜索");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "Ctrl+F";
                }
            }

            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("开始截图");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "Ctrl+C";
                }
            }
        }
    }

    HorizontalLayout {
        alignment: start;
        spacing: 20px;
        Text {
            text: @tr("当前版本 {}", version);
            height: 30px;
            width: 100px;
            vertical-alignment: center;
        }
        check_update_btn := Button {
            text: "检查更新";
            clicked => {root.check_update();}
        }
    }
}
