import { GroupBox, LineEdit } from "std-widgets.slint";
import { Page } from "page.slint";

export component ScreenShotterSettingPage inherits Page {
    GroupBox {
        title: @tr("快捷键");
        VerticalLayout {
            spacing: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("关闭贴图");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "ESC";
                }
            }
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("复制贴图");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "Enter";
                }
            }
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("保存贴图");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "S";
                }
            }
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("隐藏贴图");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "H";
                }
            }
        }
    }

    GroupBox {
        title: @tr("其他");
        VerticalLayout {
            spacing: 10px;
            HorizontalLayout {
                alignment: start;
                spacing: 20px;
                Text {
                    text: @tr("默认保存路径");
                    height: 30px;
                    width: 100px;
                    vertical-alignment: center;
                }
                LineEdit {
                    height: 30px;
                    enabled: false;
                    text: "与上次路径一致";
                }
            }
        }
    }
}