import { ComboBox, LineEdit } from "std-widgets.slint";
import { Page } from "page.slint";

export component SearchSettingPage inherits Page {
    HorizontalLayout { // TODO exclude path
        alignment: start;
        spacing: 20px;
        Text {
            text: @tr("排除路径");
            height: 30px;
            width: 100px;
            vertical-alignment: center;
        }
        LineEdit {
            height: 30px;
            read-only: true;
            text: "???";
        }
    }
}