[package]
name = "xtask"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
serde_json = { workspace = true, features = ["preserve_order"] }
toml.workspace = true
sha2.workspace = true
rotor-common.workspace = true
rotor-updater.workspace = true
minisign = "=0.9.1"
semver.workspace = true
toml_edit = "=0.22.27"
url.workspace = true
plist.workspace = true
tempfile.workspace = true
