import { BaseWindow } from "./frame/base_win.slint";

import { SettingWindow } from "./setting/setting_win.slint";

import { SearchWindow } from "./searcher/searcher_win.slint";

import { PinWindow } from "./screen_shotter/pin_win.slint";
import { ToolbarWindow } from "./screen_shotter/toolbar_win.slint";
import { MaskWindow } from "./screen_shotter/mask_win.slint";

export { 
    BaseWindow,
    SettingWindow,
    SearchWindow,
    PinWindow, ToolbarWindow, MaskWindow
}