

export component PinWindow inherits Window {
    no-frame: true;
    always-on-top: true;

    drag_box := Rectangle {
        background: red;
        height: 100px;
        width: 100px;

        TouchArea {
            moved => {
                drag_box.x = self.mouse-x - self.pressed-x;
                drag_box.y = self.mouse-y - self.pressed-y;
            }
        }
    }
}