import { VerticalBox, ScrollView, Palette, GroupBox } from "std-widgets.slint";

export component Page inherits ScrollView {
    VerticalBox{
        alignment: start;
        padding: 10px;
        padding-left: 30px;
        @children
    }
}

export component ShortcutEdit inherits Rectangle {
    border-radius: 5px;
    width: 150px;
    border-width: 1px;
    in-out property <string> shortcut_text;
    property <bool> active: false;
    callback shortcut_changed(KeyEvent);
    FocusScope {
        Text {
            text: shortcut_text;
            vertical-alignment: center;
        }
        
        focus-changed-event() => { parent.active = self.has-focus; }

        key-released(event) => {
            shortcut_changed(event);
            accept
        }
    }

    states [
        active when active: {
            border-color: Palette.accent-background;
        }
        inactive when !active: {
            border-color: Palette.alternate-background;
        }
    ]
}

export component SettingNode inherits HorizontalLayout {
    alignment: space-between;
    in-out property <string> key;
    Text {
        text: key;
        height: 30px;
        vertical-alignment: center;
    }
    @children
}

export component SettingGroup inherits GroupBox {
    VerticalLayout {
        padding-left: 20px;
        padding-right: 50px;
        spacing: 5px;
        @children
    }
}