import { Palette } from "std-widgets.slint";

export component BaseWindow inherits Window {
    default-font-size: 14px;
    icon: @image-url("../assets/logo.png");
    no-frame: true;
    background: transparent;

    // public function change_theme(theme: int) { 
    //     if theme == 0 {
    //         Palette.color-scheme = ColorScheme.unknown;
    //     } else if theme == 1 {
    //         Palette.color-scheme = ColorScheme.dark;
    //     } else if theme == 2 {
    //         Palette.color-scheme = ColorScheme.light;
    //     }
    // }
}