import { Palette } from "std-widgets.slint";

export enum ButtonType {
    Icon,
    Text,
}

export component SimpleBtn inherits Rectangle {
    background: transparent;
    animate background { duration: 150ms; }

    in property <image> icon;
    in property<string> text;
    in property <ButtonType> type: ButtonType.Icon;
    in property <color> hover_color: Palette.accent-background;
    in property <color> active_color: Palette.accent-background;
    in property <bool> active: false;
    
    callback clicked <=> touch.clicked;

    touch := TouchArea {
        if type == ButtonType.Icon: Image {
            source: icon;
            height: 16px;
            width: 16px;
            colorize: Palette.foreground;
            image-rendering: pixelated;
        }
        if type == ButtonType.Text: Text {
            text: text;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }

    states [
        pressed when touch.pressed : {
            root.background: hover_color.darker(0.5);
        }
        hover when touch.has-hover : {
            root.background: hover_color;
        }
        active when self.active:{
            root.background: active_color;
        }
    ]
}