import { BaseWindow } from "../frame/base_win.slint";

struct Rect {
    x: int,
    y: int,
    width: int,
    height: int,
}
export component MaskWindow inherits BaseWindow {
    forward-focus: focus_scope;
    title: "截图窗口";
    
    property <Point> mouse_down_pos;
    property <Point> mouse_move_pos;

    in property <image> bac_image;
    in property <bool> color_type_Dec: true;
    in property <string> color_str: "RGB:(???,???,???)";
    
    in-out property <bool> detected: false;
    in-out property <Rect> select_rect;
    in-out property <bool> mouse_left_press;

    width: bac_image.width * 1phx;
    height: bac_image.height * 1phx;
    
    callback shot();
    callback key_released(KeyEvent);
    callback new_pin_win(Rect);
    callback mouse_move(float, float, bool, bool);
    
    always-on-top: true;

    bac-img := Image {
        height: 100%;
        width: 100%;
        image-rendering: pixelated;
        source: bac_image;
        
        Rectangle {
            background: black.with_alpha(0.5);
            focus_scope := FocusScope {
                key-released(event) => {
                    if event.modifiers.shift == false {
                        root.key_released(event);
                    }
                    accept
                }
            }

            touch_area := TouchArea {
                mouse-cursor: crosshair;

                pointer-event(event) => {
                    root.mouse_move(
                        self.mouse-x / 1px, self.mouse-y / 1px,
                        root.color_type_Dec,
                        !mouse_left_press && event.modifiers.control
                    );
                    if(event.button == PointerEventButton.left) {
                        if(event.kind == PointerEventKind.down) {
                            root.mouse_left_press = true;
                            root.mouse_down_pos.x = clamp(touch_area.mouse-x, 0, root.width);
                            root.mouse_down_pos.y = clamp(touch_area.mouse-y, 0, root.height);
                            root.mouse_move_pos.x = clamp(touch_area.mouse-x, 0, root.width);
                            root.mouse_move_pos.y = clamp(touch_area.mouse-y, 0, root.height);
                        } else if (event.kind == PointerEventKind.up) {
                            root.new_pin_win(root.select_rect);
                            root.mouse_left_press = false;
                            root.select-rect.x = -1;
                            root.select-rect.y = -1;
                            root.select-rect.width = 0;
                            root.select-rect.height = 0;
                        }
                    } else if !mouse_left_press && !event.modifiers.control {
                        root.select-rect.x = -1;
                        root.select-rect.y = -1;
                        root.select-rect.width = 0;
                        root.select-rect.height = 0;
                    }
                }
                moved() => {
                    if(mouse_left_press == true) {
                        root.mouse_move_pos.x = clamp(touch_area.mouse-x, 0, root.width);
                        root.mouse_move_pos.y = clamp(touch_area.mouse-y, 0, root.height);
                        root.select-rect.x = ceil(min(root.mouse_down_pos.x, root.mouse_move_pos.x) / 1phx);
                        root.select-rect.y = ceil(min(root.mouse_down_pos.y, root.mouse_move_pos.y) / 1phx);
                        root.select-rect.width = ceil(abs(( root.mouse_move_pos.x - root.mouse_down_pos.x) / 1phx));
                        root.select-rect.height = ceil(abs(( root.mouse_move_pos.y - root.mouse_down_pos.y) / 1phx));
                    }
                }
            }

            select_border := Rectangle {
                border-color: rgb(0, 175, 255);
                border-width: 1phx;

                x: root.select-rect.x * 1phx - self.border-width;
                y: root.select-rect.y* 1phx - self.border-width;
                width: root.select-rect.width * 1phx + self.border-width * 2;
                height: root.select-rect.height * 1phx + self.border-width * 2;

                select_win := Image {
                    source: bac_image;
                    image-fit: fill;

                    x: select_border.border-width;
                    y: select_border.border-width;
                    width: root.select-rect.width * 1phx;
                    height: root.select-rect.height * 1phx;
                    
                    source-clip-x: root.select-rect.x;
                    source-clip-y: root.select-rect.y;
                    source-clip-width: root.select-rect.width;
                    source-clip-height: root.select-rect.height;
                }
            }
        }
    }

    amplifier := Rectangle {
        width: 120px;
        height:176px; // 90px + 78px + 2px * 4
        x: ((touch-area.mouse-x) + self.width > root.width) ? 
            min(touch-area.mouse-x, root.width) - self.width : max(touch-area.mouse-x, 0);
        y: ((touch-area.mouse-y) + 25px + self.height > root.height) ? 
            min((touch-area.mouse-y) - 25px, root.height) - self.height : max(touch-area.mouse-y + 25px, 0);
        background: black.with_alpha(0.6);

        VerticalLayout {
            alignment: start;
            spacing: 2px;
            Rectangle {
                width: 100%;
                height: 90px;
                border-width: 1px;
                border-color: white;
                
                Image {
                    width: (parent.width) - 2px;
                    height: (parent.height) - 2px;
                    source: bac_image;
                    image-fit: fill;
                    source-clip-x: touch-area.mouse-x / 1phx - self.width / 8phx;
                    source-clip-y: touch-area.mouse-y / 1phx - self.height / 8phx;
                    source-clip-width: self.width / 4phx;
                    source-clip-height: self.height / 4phx;
                }
            }

            Text {
                horizontal-alignment: center;
                text: touch_area.pressed ?
                    @tr(
                        "宽{}×高{}",
                        root.select_rect.width, root.select_rect.height
                    ) : @tr("左键划选区域");
                color: white;
            } // draw width and height

            Text {
                horizontal-alignment: center;
                text: color_str;
                color: white;
            } // draw RGB color code

            Text {
                horizontal-alignment: center;
                text: @tr("Z切换 C复制");
                color: white;
            } // draw tips

            Text {
                horizontal-alignment: center;
                text: @tr("按住Ctrl智能选区");
                color: white;
            } // auto detect tips
        }

        // draw cross curve
        Path {
            x: 0;
            y: 0;
            width: 100%;
            height: 90px;
            commands: "M 60 0 v 90";
            stroke: rgba(0, 180, 255, 0.7);
            stroke-width: 2px;
        } // draw vertical lines

        Path {
            x: 0;
            y: 0;
            width: 100%;
            height: 90px;
            commands: "M 0 45 L 120 45";
            stroke: rgba(0, 180, 255, 0.7);
            stroke-width: 2px;
        } // draw horizontal lines
    }
}