[package]
name = "rotor-screenshot"
version.workspace = true
edition = "2021"

[dependencies]
rotor-canvas.workspace = true
image.workspace = true
log.workspace = true
oar-ocr = "0.7.1"
rayon = "1.10"
rotor-common.workspace = true
rotor-platform.workspace = true
serde.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
