[package]
name = "rotor-screenshot"
version.workspace = true
edition = "2021"

[dependencies]
rotor-canvas = { path = "../rotor-canvas" }
image.workspace = true
log = "0.4.27"
oar-ocr = "0.7.1"
rayon = "1.10"
rotor-common = { path = "../rotor-common" }
rotor-platform = { path = "../rotor-platform" }
serde = { version = "1", features = ["derive"] }
toml = "0.8.23"

[dev-dependencies]
tempfile = "=3.27.0"
