[package]
name = "rotor-translator"
version.workspace = true
edition = "2021"

[dependencies]
reqwest = { version = "0.13", default-features = false, features = [
  "rustls-no-provider",
  "json",
  "query",
] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rotor-common = { path = "../rotor-common" }
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
