[package]
name = "rotor-translator"
version.workspace = true
edition = "2021"

[dependencies]
reqwest = { workspace = true, features = ["query"] }
rustls.workspace = true
rotor-common.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
