[package]
name = "rotor-ui"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
base64 = "0.22.1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
image.workspace = true
log = "0.4"
lyon = "1"
global-hotkey = "=0.7.0"
gpui-kit.workspace = true
gpui.workspace = true
rotor-common.workspace = true
rotor-runtime.workspace = true
rotor-canvas.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
tempfile = "3"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.61.3", features = ["Win32_UI_Controls", "Win32_UI_Accessibility", "Win32_UI_HiDpi", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi"] }
