[package]
name = "rotor-ui"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
base64 = "0.22.1"
image.workspace = true
global-hotkey = "=0.7.0"
gpui-kit.workspace = true
gpui.workspace = true
rotor-common.workspace = true
rotor-runtime.workspace = true
rotor-canvas.workspace = true
