[package]
name = "rotor-ui"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
image.workspace = true
log.workspace = true
lyon = "1"
global-hotkey.workspace = true
gpui-kit.workspace = true
gpui.workspace = true
rotor-common.workspace = true
rotor-runtime.workspace = true
rotor-canvas.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
