[package]
name = "rotor-desktop"
version.workspace = true
edition = "2024"
publish = false
default-run = "rotor-desktop"

[features]
production = ["rotor-common/production"]

[dependencies]
gpui-kit.workspace = true
gpui.workspace = true
gpui-platform.workspace = true
rotor-common.workspace = true
rotor-runtime.workspace = true
rotor-platform.workspace = true
async-channel.workspace = true
futures.workspace = true
image.workspace = true
global-hotkey.workspace = true
tray-icon = "=0.21.3"
rotor-ui.workspace = true
rotor-canvas.workspace = true
rotor-updater.workspace = true
raw-window-handle.workspace = true
log = { workspace = true, features = ["std"] }
tempfile.workspace = true

[build-dependencies]
embed-resource = "=3.0.9"
