[package]
name = "rotor-desktop"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
gpui-kit.workspace = true
gpui.workspace = true
gpui-platform.workspace = true
rotor-common.workspace = true
rotor-runtime.workspace = true
rotor-platform.workspace = true
async-channel.workspace = true
futures.workspace = true
image.workspace = true
global-hotkey = "=0.7.0"
tray-icon = "=0.21.3"
rotor-ui.workspace = true
rotor-canvas.workspace = true
rotor-updater.workspace = true
raw-window-handle = "=0.6.2"
log = { version = "0.4", features = ["std"] }

[build-dependencies]
embed-resource = "=3.0.9"
