name: Build And Release App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: build and release app

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Get latest tag
        run: |
          $latestTag = git describe --tags $(git rev-list --tags --max-count=1)
          echo "Latest tag is $latestTag"
          echo "LATEST_TAG=$latestTag" >> $GITHUB_ENV
          
      - name: Build
        run: cargo build --release

      - name: Compress
        run: Compress-Archive -Path assets, target\release\rotor.exe -DestinationPath rotor-$LATEST_TAG.zip

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "rotor-$LATEST_TAG.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
